databases:
  cached-drops:
    type: mysql
    credentials:
      host: localhost
      port: 3306
      username: root
      password: password
      database: test
  queued-drops:
    type: sqlite
    credentials:
      database: test