ranges:
  supply-drop:
    min: 1
    max: 5
  gg-drop:
    min: 1
    max: 5


notification-times: [5 minutes, 10 minutes, 15 minutes, 20 minutes, 25 minutes, 30 minutes]

drop-velocity-multiplier: -0.2 # Tweak this to liking
default-drop: "supply-drop"

time-per-supply-drop: 30 minutes
player-location-height: 150

circle:
  particle: "SPELL_WITCH"
  radius: 0.875
  delay: 1